import os
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv()

def load_news():
    try:
        # Assuming run from root directory
        file_path = "summarized_news.json"
        
        # Fallback if in subdirectory
        if not os.path.exists(file_path):
             file_path = "../summarized_news.json"
             
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print("[ERROR] summarized_news.json not found. Run app.py first.")
        return []

def format_email_body(articles, recipient_email):
    base_url = os.environ.get("BASE_URL", "http://127.0.0.1:8000")
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #2c3e50; color: white; padding: 15px; text-align: center; border-radius: 5px 5px 0 0; }}
            .article {{ border: 1px solid #ddd; border-top: none; padding: 15px; margin-bottom: 0; background-color: #fff; }}
            .article:first-of-type {{ border-top: 1px solid #ddd; }}
            .source {{ color: #e74c3c; font-weight: bold; font-size: 0.9em; }}
            .title {{ color: #2c3e50; font-size: 1.2em; margin: 5px 0; font-weight: bold; }}
            .summary {{ color: #555; background-color: #f9f9f9; padding: 10px; border-left: 4px solid #3498db; border-radius: 3px; }}
            .footer {{ text-align: center; font-size: 0.8em; color: #888; margin-top: 20px; padding: 10px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Daily News Brief</h2>
                <p>{datetime.now().strftime('%B %d, %Y')}</p>
            </div>
    """

    for article in articles:
        source = article.get("source", "Unknown Source")
        title = article.get("title", "No Title")
        summary = article.get("summary", "No Summary Available").replace("\n", "<br>")
        url = article.get("url", "")
        
        link_html = f'<div style="margin-top: 10px;"><a href="{url}" target="_blank" style="color: #3498db; text-decoration: none; font-size: 0.9em; font-weight: bold;">Read full story &rarr;</a></div>' if url else ""

        html += f"""
            <div class="article">
                <div class="source">{source}</div>
                <div class="title">{title}</div>
                <div class="summary">{summary}</div>
                {link_html}
            </div>
        """

    html += f"""
            <div class="footer">
                <p>Generated by AI News Agent</p>
                <p style="margin-top: 15px; font-size: 0.9em;">
                    Want to change your topics? <a href="{base_url}/?email={recipient_email}" style="color: #3498db;">Update your preferences</a><br>
                    No longer want these emails? <a href="{base_url}/unsubscribe?email={recipient_email}" style="color: #e74c3c;">Unsubscribe</a>
                </p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_email(recipient_email, subject, body_html):
    sender_email = os.environ.get("GMAIL_USER")
    sender_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not all([sender_email, sender_password]):
        print("[ERROR] Missing email configuration in .env file.")
        return

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = subject

    msg.attach(MIMEText(body_html, 'html'))

    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, [recipient_email], msg.as_string())
        print(f"Email sent successfully to: {recipient_email}")
    except Exception as e:
        print(f"[ERROR] Failed to send email to {recipient_email}: {e}")

def send_welcome_email(recipient_email):
    sender_email = os.environ.get("GMAIL_USER")
    sender_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not all([sender_email, sender_password]):
        print("[ERROR] Missing email configuration in .env file.")
        return

    base_url = os.environ.get("BASE_URL", "http://127.0.0.1:8000")
    subject = "Welcome to NewsCraft!"
    body_html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #2c3e50; color: white; padding: 15px; text-align: center; border-radius: 5px 5px 0 0; }}
            .content {{ padding: 20px; background-color: #fff; border: 1px solid #ddd; border-top: none; }}
            .footer {{ text-align: center; font-size: 0.8em; color: #888; margin-top: 20px; padding: 10px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Welcome to NewsCraft!</h2>
            </div>
            <div class="content">
                <h3>Thanks for subscribing!</h3>
                <p>We're thrilled to have you on board. From now on, you'll receive a curated summary of the latest top news every 24 hours.</p>
                <p>Stay tuned for your first update!</p>
            </div>
            <div class="footer">
                <p>Generated by AI News Agent</p>
                <p style="margin-top: 15px; font-size: 0.9em;">
                    Want to change your topics? <a href="{base_url}/?email={recipient_email}" style="color: #3498db;">Update your preferences</a><br>
                    No longer want these emails? <a href="{base_url}/unsubscribe?email={recipient_email}" style="color: #e74c3c;">Unsubscribe</a>
                </p>
            </div>
        </div>
    </body>
    </html>
    """
    
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body_html, 'html'))

    try:
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, [recipient_email], msg.as_string())
        print(f"Welcome email sent to {recipient_email}")
    except Exception as e:
        print(f"[ERROR] Failed to send welcome email: {e}")


def main():
    print(">>> Reading News Data...")
    all_news = load_news()
    
    if not all_news:
        print("No articles to send.")
        return

    # Connect to MongoDB
    mongo_uri = os.environ.get("MONGODB_URI")
    subscribers = []
    
    if mongo_uri:
        try:
            import certifi
            client = MongoClient(mongo_uri, tlsCAFile=certifi.where())
            db = client.newscraft
            subs_cursor = db.subscribers.find({})
            for sub in subs_cursor:
                subscribers.append(sub)
        except Exception as e:
            print(f"[ERROR] Could not connect to MongoDB: {e}")
            
    # Also support old env recipients
    recipients_str = os.environ.get("RECIPIENT_EMAILS")
    if recipients_str:
        env_recipients = [email.strip() for email in recipients_str.split(",") if email.strip()]
        for er in env_recipients:
            if not any(sub.get("email") == er for sub in subscribers):
                subscribers.append({"email": er, "genres": []})

    if not subscribers:
        print("No subscribers found.")
        return

    subject = f"AI News Brief - {datetime.now().strftime('%d %b %Y')}"

    for sub in subscribers:
        # handle string back-compat
        if isinstance(sub, str):
            email = sub
            genres = []
        else:
            email = sub.get("email")
            genres = sub.get("genres", [])
            
        if not email:
            continue
            
        # Collect articles for this user
        user_articles = []
        if not genres:
            # Send top news if no genre selected
            user_articles = all_news.get("Top News", [])
        else:
            for genre in genres:
                user_articles.extend(all_news.get(genre, []))
                
        if not user_articles:
            print(f"No news matches for user {email}, skipping.")
            continue
            
        body_html = format_email_body(user_articles, email)
        send_email(email, subject, body_html)


if __name__ == "__main__":
    main()
